application:
  hooks:
    pre-app-build: npm run build
  runtimeManifest:
    packages:
      main:
        license: Apache-2.0
        actions:
          rockwell:
            function: dist/rockwell
            web: 'yes'
            runtime: 'nodejs:18'
            inputs:
              LOG_LEVEL: debug
              rockwellOrigin: $ROCKWELL_ORIGIN
              rockwellClientId: $ROCKWELL_CLIENT_ID
              rockwellClientSecret: $ROCKWELL_CLIENT_SECRET
            annotations:
              require-adobe-auth: false # explicitly unauthenticated action
              final: true
