/**
 * see https://github.com/valeriangalliat/markdown-it-anchor/blob/69cbf727367c6b10a553a8549790a6d6df917342/index.js#L12
 *
 * Due to markdown-it-anchor and how it slugifies the id, we need to check if the id is a `-` followed by a number
 * this indicates that the id was generated by markdown-it-anchor for an empty ID and we dont have to add our anchor for it.
 *
 * @param {string} id
 */
const isMarkdownItGeneratedId = (id) => /^-\d+$/g.test(id);

/**
 * the helix html2md pipeline disregards any "id" attributes on headers (and other els I believe)
 * so we need a way for these ids to survive the html2md pipeline. These IDs are used as anchors.
 * Here, we suffix the heading text with an icon whose name is anchor-<heading id>.
 * On the FE, we will use this icon name to restore the "id" on the heading.
 *
 * Due to markdown-it-anchor and how it slugifies the id, we need to check if the id is a `-`followed by a number
 * this indicates that the id was generated by markdown-it-anchor and is not
 * @param {Document} document
 */
export const updateAnchors = (document) => {
  document.querySelectorAll('h1, h2, h3, h4, h5, h6').forEach((headingEl) => {
    // check if id matches -1 AKA - followed by any number of digits
    if (headingEl.id) {
      if (!isMarkdownItGeneratedId(headingEl.id)) {
        headingEl.appendChild(document.createTextNode(` :headding-anchor:`));
        headingEl.appendChild(document.createTextNode(headingEl.id));
      }
    }
  });
};
